on:
  push:
    branches:
      - main

jobs:
  deploy_assets:
    runs-on: ubuntu-latest
    env:
      destination: assets/specs-2026/
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v5

      - name: Upload to incubation.w3.org bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          aws s3 sync --no-progress js s3://incubation.w3.org/${{ env.destination }}
          aws s3 sync --no-progress css s3://incubation.w3.org/${{ env.destination }}

